# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20191125_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosdeinteresse',
            name='localizacao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rotasdeinteresse',
            name='horario',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rotasdeinteresse',
            name='localizacao_atual',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rotasdeinteresse',
            name='localizacao_final',
            field=models.CharField(max_length=250),
        ),
    ]
