# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-25 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_auto_20191125_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Motorista'),
        ),
    ]
